import type { ToolCategory, ToolDefinition, ToolStatus } from '../types/tool';

export const categoryLabels: Record<ToolCategory, string> = {
  format: '格式转换',
  time: '时间处理',
  text: '文本处理',
  generator: '内容生成',
  image: '图片处理',
};

export const statusLabels: Record<ToolStatus, string> = {
  online: 'Online',
  beta: 'Beta',
  planned: 'Planned',
  disabled: 'Disabled',
};

export const tools: ToolDefinition[] = [
  {
    id: 'json-formatter',
    name: 'JSON 格式化器',
    shortName: 'JSON',
    description: '格式化、压缩、校验 JSON，并定位常见语法错误。',
    route: '/json-formatter/',
    category: 'format',
    status: 'online',
    featured: true,
    order: 1,
    keywords: ['JSON', 'format', 'minify', 'validate', '格式化', '压缩', '校验'],
    icon: '/icons/json.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'timestamp-converter',
    name: '时间戳转换器',
    shortName: 'Timestamp',
    description: '在 Unix 时间戳、日期、UTC、本地时间和指定时区之间转换。',
    route: '/timestamp-converter/',
    category: 'time',
    status: 'online',
    featured: true,
    order: 2,
    keywords: ['timestamp', 'Unix', 'UTC', 'timezone', '时间戳', '时区', '日期'],
    icon: '/icons/timestamp.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'text-counter',
    name: '文本统计器',
    shortName: 'Counter',
    description: '统计可见字符、中文、英文单词、段落、字节数和阅读时间。',
    route: '/text-counter/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 3,
    keywords: ['text', 'word count', 'character', '字符统计', '字数', '阅读时间'],
    icon: '/icons/text-counter.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'text-line-processor',
    name: '文本去重与排序',
    shortName: 'Lines',
    description: '按行去重、清理空白，并进行自然、数字或字典序排序。',
    route: '/text-line-processor/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 4,
    keywords: ['lines', 'deduplicate', 'sort', '文本去重', '文本排序', '自然排序', '数字排序'],
    icon: '/icons/line-processor.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'qr-code-generator',
    name: '二维码生成器',
    shortName: 'QR Code',
    description: '在浏览器本地生成文本、URL、邮箱、电话和 Wi-Fi 二维码。',
    route: '/qr-code-generator/',
    category: 'generator',
    status: 'online',
    featured: true,
    order: 5,
    keywords: ['QR code', 'qrcode', 'PNG', 'SVG', '二维码', 'Wi-Fi', 'URL'],
    icon: '/icons/qrcode.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'base64-codec',
    name: 'Base64 编解码',
    shortName: 'Base64',
    description: '在浏览器本地完成文本、Base64 和文件字节的转换。',
    route: '/base64-codec/',
    category: 'format',
    status: 'online',
    featured: true,
    order: 6,
    keywords: ['Base64', 'encode', 'decode', 'UTF-8', '文件编码', '中文', '编解码'],
    icon: '/icons/base64.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'url-codec',
    name: 'URL 编解码',
    shortName: 'URL',
    description: '编码、解码、解析 URL，并展开 Query 参数。',
    route: '/url-codec/',
    category: 'format',
    status: 'online',
    featured: true,
    order: 7,
    keywords: ['URL', 'encodeURI', 'encodeURIComponent', 'Query', '参数', '编码', '解码'],
    icon: '/icons/url.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'uuid-generator',
    name: 'UUID 生成器',
    shortName: 'UUID',
    description: '用浏览器安全随机数批量生成、复制和去重 UUID v4。',
    route: '/uuid-generator/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 8,
    keywords: ['UUID', 'v4', 'GUID', 'random', '批量生成', '去重'],
    icon: '/icons/uuid.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'text-diff',
    name: '文本对比工具',
    shortName: 'Diff',
    description: '左右对比两段文本，实时高亮新增与删除内容。',
    route: '/text-diff/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 9,
    keywords: ['diff', 'compare', '文本对比', '差异', '新增', '删除'],
    icon: '/icons/diff.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    shortName: 'Regex',
    description: '实时查看匹配、捕获分组、替换结果和常用模板。',
    route: '/regex-tester/',
    category: 'text',
    status: 'online',
    featured: true,
    order: 10,
    keywords: ['regex', 'RegExp', 'match', 'replace', '正则', '分组', '替换'],
    icon: '/icons/regex.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT 解码器',
    shortName: 'JWT',
    description: '本地解码 JWT Header、Payload，并查看过期状态。',
    route: '/jwt-decoder/',
    category: 'format',
    status: 'online',
    featured: false,
    order: 11,
    keywords: ['JWT', 'JSON Web Token', 'token', 'Header', 'Payload', '过期时间'],
    icon: '/icons/jwt.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'hash-calculator',
    name: '哈希计算工具',
    shortName: 'Hash',
    description: '在浏览器本地计算文本或文件的 MD5、SHA-1、SHA-256、SHA-512。',
    route: '/hash-calculator/',
    category: 'generator',
    status: 'online',
    featured: true,
    order: 12,
    keywords: ['hash', 'MD5', 'SHA-1', 'SHA-256', 'SHA-512', '文件校验'],
    icon: '/icons/hash.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 预览',
    shortName: 'Markdown',
    description: '左侧编辑 Markdown，右侧安全地实时渲染预览。',
    route: '/markdown-preview/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 13,
    keywords: ['Markdown', 'preview', 'editor', 'md', '预览', '编辑器'],
    icon: '/icons/markdown.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-compressor',
    name: '图片压缩',
    shortName: 'Compress',
    description: '使用浏览器 Canvas 在本地压缩图片并预览体积变化。',
    route: '/image-compressor/',
    category: 'image',
    status: 'online',
    featured: true,
    order: 14,
    keywords: ['image', 'compress', 'JPG', 'WebP', '图片压缩', '体积优化'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-resizer',
    name: '图片尺寸调整',
    shortName: 'Resize',
    description: '在浏览器本地调整图片宽高，并可保持原始比例。',
    route: '/image-resizer/',
    category: 'image',
    status: 'online',
    featured: true,
    order: 15,
    keywords: ['image', 'resize', '尺寸', '宽高', '图片调整'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-converter',
    name: 'PNG/JPG/WebP 转换',
    shortName: 'Convert',
    description: '本地转换 PNG、JPG、WebP 输出格式与质量。',
    route: '/image-converter/',
    category: 'image',
    status: 'online',
    featured: true,
    order: 16,
    keywords: ['PNG', 'JPG', 'WebP', 'convert', '图片转换', '格式转换'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-cropper',
    name: '图片裁剪',
    shortName: 'Crop',
    description: '按像素范围裁剪本地图片，导出 PNG 结果。',
    route: '/image-cropper/',
    category: 'image',
    status: 'online',
    featured: false,
    order: 17,
    keywords: ['image', 'crop', '图片裁剪', '裁剪尺寸'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-rounded-corners',
    name: '图片圆角处理',
    shortName: 'Round',
    description: '在浏览器本地为图片生成透明圆角 PNG。',
    route: '/image-rounded-corners/',
    category: 'image',
    status: 'online',
    featured: false,
    order: 18,
    keywords: ['image', 'rounded corner', '圆角', '图片圆角'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-base64',
    name: '图片转 Base64',
    shortName: 'Image Base64',
    description: '将本地图片转换为可复制的 Data URL Base64。',
    route: '/image-base64/',
    category: 'image',
    status: 'online',
    featured: false,
    order: 19,
    keywords: ['image', 'Base64', 'Data URL', '图片转Base64'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'ico-generator',
    name: 'ICO 图标生成',
    shortName: 'ICO',
    description: '从本地图片生成不同尺寸的 PNG 封装 ICO 图标。',
    route: '/ico-generator/',
    category: 'image',
    status: 'online',
    featured: false,
    order: 20,
    keywords: ['ICO', 'favicon', 'icon', '图标生成'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'image-color-picker',
    name: '图片取色器',
    shortName: 'Image Color',
    description: '点击本地图片像素，读取 HEX、RGB 和 HSL 色值。',
    route: '/image-color-picker/',
    category: 'image',
    status: 'online',
    featured: false,
    order: 21,
    keywords: ['image', 'color picker', '取色', '颜色'],
    icon: '/icons/image.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'text-case-converter',
    name: '大小写转换',
    shortName: 'Case',
    description: '转换为小写、大写、标题格式或句首大写。',
    route: '/text-case-converter/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 22,
    keywords: ['case', 'uppercase', 'lowercase', '大小写', '标题格式'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'naming-converter',
    name: '命名转换',
    shortName: 'Naming',
    description: '在 camel、snake、kebab、Pascal 等命名之间转换。',
    route: '/naming-converter/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 23,
    keywords: ['camelCase', 'snake_case', 'kebab-case', '命名转换'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'whitespace-cleaner',
    name: '空格和空行清理',
    shortName: 'Clean',
    description: '清理每行空白、连续空格和多余空行。',
    route: '/whitespace-cleaner/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 24,
    keywords: ['whitespace', 'blank line', '空格清理', '空行'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'find-replace',
    name: '查找替换',
    shortName: 'Replace',
    description: '按普通文本进行大小写敏感或批量查找替换。',
    route: '/find-replace/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 25,
    keywords: ['find', 'replace', '查找', '替换'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'random-string-generator',
    name: '随机字符串生成',
    shortName: 'Random',
    description: '用浏览器安全随机数生成可配置的随机字符串。',
    route: '/random-string-generator/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 26,
    keywords: ['random', 'string', 'password', '随机字符串'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum 生成',
    shortName: 'Lorem',
    description: '按段落和单词数量生成本地排版占位文本。',
    route: '/lorem-ipsum-generator/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 27,
    keywords: ['Lorem', 'Ipsum', 'placeholder', '占位文本'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'contact-extractor',
    name: 'URL、邮箱、手机号提取',
    shortName: 'Extract',
    description: '从文本中本地提取、去重 URL、邮箱和大陆手机号。',
    route: '/contact-extractor/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 28,
    keywords: ['URL', 'email', 'phone', '提取', '邮箱', '手机号'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'hidden-character-detector',
    name: '隐藏字符检测',
    shortName: 'Hidden',
    description: '定位零宽字符、BOM、不换行空格、制表符等不可见字符。',
    route: '/hidden-character-detector/',
    category: 'text',
    status: 'online',
    featured: false,
    order: 29,
    keywords: ['zero width', 'BOM', 'hidden character', '隐藏字符', '零宽'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'color-converter',
    name: 'HEX/RGB/HSL 转换',
    shortName: 'Color',
    description: '实时转换 HEX、RGB、HSL，并预览当前颜色。',
    route: '/color-converter/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 30,
    keywords: ['HEX', 'RGB', 'HSL', 'color', '颜色转换'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'color-picker',
    name: '颜色选择器',
    shortName: 'Picker',
    description: '用本地原生颜色面板选择颜色并获得 CSS 色值。',
    route: '/color-picker/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 31,
    keywords: ['color picker', '颜色选择器', 'HEX', 'RGB'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'gradient-generator',
    name: '渐变色生成器',
    shortName: 'Gradient',
    description: '交互生成线性渐变预览和可复制的 CSS。',
    route: '/gradient-generator/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 32,
    keywords: ['gradient', 'linear-gradient', '渐变色', 'CSS'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'css-shadow-generator',
    name: 'CSS 阴影生成器',
    shortName: 'Shadow',
    description: '调整偏移、模糊、扩展和颜色，生成 box-shadow。',
    route: '/css-shadow-generator/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 33,
    keywords: ['box-shadow', 'shadow', '阴影', 'CSS'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'css-radius-generator',
    name: 'CSS 圆角生成器',
    shortName: 'Radius',
    description: '独立调整四角半径，生成 border-radius CSS。',
    route: '/css-radius-generator/',
    category: 'generator',
    status: 'online',
    featured: false,
    order: 34,
    keywords: ['border-radius', 'radius', '圆角', 'CSS'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'rem-px-converter',
    name: 'REM/PX 转换',
    shortName: 'REM',
    description: '基于自定义根字号计算 px 与 rem 的换算。',
    route: '/rem-px-converter/',
    category: 'format',
    status: 'online',
    featured: false,
    order: 35,
    keywords: ['rem', 'px', 'font size', '单位转换'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'screen-ratio-calculator',
    name: '屏幕尺寸与比例计算',
    shortName: 'Ratio',
    description: '计算屏幕、画布或视频尺寸的最简比例和方向。',
    route: '/screen-ratio-calculator/',
    category: 'format',
    status: 'online',
    featured: false,
    order: 36,
    keywords: ['screen', 'aspect ratio', '16:9', '屏幕尺寸', '比例'],
    icon: '/icons/design.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'token-estimator',
    name: 'Token 数量估算',
    shortName: 'Tokens',
    description: '按中英混合、中文密集、英文/代码三种本地模型估算 Token。',
    route: '/token-estimator/',
    category: 'text',
    status: 'online',
    featured: true,
    order: 37,
    keywords: ['token', 'tokens', 'LLM', 'prompt', '分词', 'Token 估算'],
    icon: '/icons/text-enhance.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'doi-reference-tool',
    name: 'DOI 检查与参考文献转换',
    shortName: 'DOI',
    description: '检查 DOI 通用格式，并输出 GB/T 7714、APA 7 或 BibTeX 参考文献。',
    route: '/doi-reference-tool/',
    category: 'format',
    status: 'online',
    featured: true,
    order: 38,
    keywords: ['DOI', 'reference', 'BibTeX', 'APA', 'GB/T 7714', '参考文献'],
    icon: '/icons/doi.svg',
    privacyMode: 'local-only',
    visible: true,
  },
  {
    id: 'experimental-data-chart',
    name: '实验数据图表',
    shortName: 'Chart',
    description: '从 CSV 或 TSV 实验数据生成本地折线、散点和柱状图。',
    route: '/experimental-data-chart/',
    category: 'generator',
    status: 'online',
    featured: true,
    order: 39,
    keywords: ['CSV', 'TSV', 'chart', 'plot', '实验数据', '图表', '折线图', '散点图'],
    icon: '/icons/chart.svg',
    privacyMode: 'local-only',
    visible: true,
  },
];

export const visibleTools = tools.filter((tool) => tool.visible).sort((a, b) => a.order - b.order);

export const availableTools = visibleTools.filter(
  (tool) => tool.status === 'online' || tool.status === 'beta',
);

export const getToolById = (id: string): ToolDefinition => {
  const tool = tools.find((item) => item.id === id);
  if (!tool) throw new Error(`Unknown tool: ${id}`);
  return tool;
};

export const getRelatedTools = (id: string, limit = 3): ToolDefinition[] => {
  const current = getToolById(id);
  return availableTools
    .filter((tool) => tool.id !== id)
    .sort((a, b) => {
      const categoryDelta =
        Number(b.category === current.category) - Number(a.category === current.category);
      return categoryDelta || a.order - b.order;
    })
    .slice(0, limit);
};
